"""first time

Revision ID: dadc8f63087c
Revises: 
Create Date: 2024-09-17 14:02:35.902540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadc8f63087c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_session',
    sa.Column('sessionUUID', sa.String(length=128), nullable=False),
    sa.Column('musicEngine', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('mei', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('humdrum', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('musicxml', sa.LargeBinary(length=4294967295), nullable=True),
    sa.PrimaryKeyConstraint('sessionUUID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_session')
    # ### end Alembic commands ###
